### ISSUE TITLE
Gateway example is not clear

### ISSUE THREAD

**Issue by sjanota** [kyma-project/examples#107]
**Description**

In [Gateway example](https://github.com/kyma-project/examples/tree/master/gateway) the flow of the document suggests, that user can expose two different APIs (secured and unsecured) at the same time while this is not possible. Only the first one will be created and the second will contain error in object status (which is not showed in UI). Example needs to be clear that two APIs may not exist at the same time. 

**Expected result**

**Actual result**

**Steps to reproduce**

Follow blindly the example ;)

**Troubleshooting**

**Comment by a-thaler** [comment]
feedback applied
