### ISSUE TITLE
Bind a Service to a Lambda Function example is not correct

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/examples#108]
**Description**

Following example is not correct: https://github.com/kyma-project/examples/blob/master/service-binding/lambda/README.md

I've encountered the following issues while executing this example step by step:
- We should create a test namespace at the beginning - before step 2.
- In the step nr. 3 there is a command to check binding status: `kubectl get servicebinding/redis-instance-binding -o jsonpath='{ .status.conditions[0].reason }' -n $KYMA_EXAMPLE_NS
`, but at this step, the binding doesn't exist, we create it in the next step.
- At the step number 6, when lambda is ready, I'm getting this error message:
```
ERRO[0000]                                              
FATA[0000] the server is currently unable to handle the request (get services redis-client:http-function-
```

**Expected result**

Example scenario can be executed step by step for anyone.

**Actual result**

We can't call lambda at the end and we get troubles with the test scenario steps

**Steps to reproduce**

Just follow the test scenario

**Comment by igor-karpukhin** [comment]
The first step with not existing namespace: it is mentioned in the `Prerequisites` section that you have to have a namespace created and labeled. As for the 3rd step: the documentation fixed in the following PR https://github.com/kyma-project/examples/pull/106

**Comment by a-thaler** [comment]
Scenario fixed in documentation, thanks for the feedback
