### ISSUE TITLE
Monitoring examples are not correct

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/examples#109]
**Description**

In both examples:
- https://github.com/kyma-project/examples/blob/master/monitoring-alert-rules/README.md
- https://github.com/kyma-project/examples/blob/master/monitoring-custom-metrics/README.md#access-the-exposed-metrics-in-prometheus

The name of prometheus pod is invalid. The correct name for this pod is `prometheus-monitoring` but in the examples we use `prometheus-core`.

- https://github.com/kyma-project/examples/blob/master/monitoring-alert-rules/README.md
Step number 2 is not working due to invalid name of the pod.
Now it is:
`kubectl port-forward pod/prometheus-core-0 -n kyma-system 9090:9090`
but it should be:
`kubectl port-forward pod/prometheus-monitoring-0 -n kyma-system 9090:9090`

- https://github.com/kyma-project/examples/blob/master/monitoring-custom-metrics/README.md#access-the-exposed-metrics-in-prometheus
Now it is:
`kubectl port-forward -n kyma-system svc/core-prometheus 9090:9090`
but is should be:
`kubectl port-forward -n kyma-system svc/monitoring-prometheus 9090:9090`

The other things from this example works normally.

**Comment by igor-karpukhin** [comment]
Example fixed in the following PR: https://github.com/kyma-project/examples/pull/106 (changed pod and service names)
Tested on the GC cluster
```
kubectl -n kyma-system get svc | grep prometheus
monitoring-prometheus                                         ClusterIP      10.47.242.85    <none>         9090/TCP                       7d
prometheus-operated                                           ClusterIP      None            <none>         9090/TCP                       7d

kubectl -n kyma-system get pods | grep prometheus
prometheus-monitoring-0                                           2/2     Running     0          7d
```

**Comment by a-thaler** [comment]
Feedback applied as described
