### ISSUE TITLE
Bind a Service to a Lambda - could not trigger the function

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/examples#120]
**Description**

The example https://github.com/kyma-project/examples/tree/master/service-binding/lambda does not work. The step "Trigger the function" gives the result:
```
ERRO[0000]
FATA[0000] an error on the server ("Error: 'EOF'
Trying to reach: 'http://10.28.3.28:8080/'") has prevented the request from succeeding (get services redis-client:http-function-port)
```

**Expected result**

The step 7 contains a command which triggers the function.

**Actual result**

Could not trigger the function

**Steps to reproduce**

Follow the test scenario

**Comment by nachtmaar** [comment]
``` kubeless function call redis-client -n $KYMA_EXAMPLE_NS

ERRO[0000]
FATA[0000] the server is currently unable to handle the request (get services redis-client:http-function-port)
```
