### ISSUE TITLE
Binding service to lambda, missing information in the example

### ISSUE THREAD

**Issue by rafaelhoff** [kyma-project/examples#126]
**Description**

I just compared the `ServiceBindingUsage` that is created via the UI against the example that is provided in https://github.com/kyma-project/examples/tree/master/service-binding/lambda.
I see that the following section is added via the UI, which is not available in the example:
```
spec:
  parameters:
    envPrefix:
      name: ""  
```

**Expected result**

The Service Binding is reflected in the UI of Lambda details.

**Actual result**

Without this parameters section in the example, the Service Binding is not displayed in the UI of Kyma.

**Steps to reproduce**

Follow the example as it is. Later just add the `parameters` section below `spec` in the ServiceBindingUsage and try it again. The Binding is then shown in the UI.

**Troubleshooting**

none.

**Comment by a-thaler** [comment]
Oh, good finding. Indeed we should fix it in the service catalog to still show it even if the attribute is nil.
