### ISSUE TITLE
Create Application Connectivity samples for various languages to make Kyma integration easier

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/examples#134]
**Description**

Applications integrating with Kyma must interact with the Application Connector API to generate certificates and register APIs. Although the Application Connector API is stable and documented, it requires users to write boilerplate code and get familiar with (sometimes) technical APIs of the respective programming languages. These constraints and efforts are seen as inhibitors to Kyma adoption. 

Although we are part of a polyglot environment the majority of modern business applications are written in:

- Java
- Node.Js
- Python
- .Net
- PHP

**Reasons**

Providing simple to use convenience libraries (examples) for developers on these platforms would speed up the understanding and initial efforts of integrating with Kyma. An example of such a convenience library is: https://github.com/akrausesap/connector/tree/master/scpxf-connector

**Comment by janmedrek** [comment]
With the shift to the Compass, this issue will be replaced by https://github.com/kyma-incubator/compass/issues/627
