### ISSUE TITLE
local build failes

### ISSUE THREAD

**Issue by igna-davidboyd** [kyma-project/examples#163]
**Description**

Following the instructions provided on the readme - the build appears to be failing with the following results

# github.com/stretchr/testify/assert
../../../stretchr/testify/assert/assertions.go:1703:5: undefined: errors.Is
../../../stretchr/testify/assert/assertions.go:1726:6: undefined: errors.Is
../../../stretchr/testify/assert/assertions.go:1749:5: undefined: errors.As
../../../stretchr/testify/assert/assertions.go:1766:7: undefined: errors.Unwrap
../../../stretchr/testify/assert/assertions.go:1770:7: undefined: errors.Unwrap
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .' returned a non-zero code: 2

**Expected result**

Build is successful

**Actual result**

Build fails which is preventing the ability to run the next step of running the docker image

**Steps to reproduce**
1. Cloned the repo on local
2. verify pre-req are present
3. run $ ./build.sh

**Troubleshooting**

**Comment by a-thaler** [comment]
Hi @igna-davidboyd ,
can you please specify which example or sub-folder you are trying to build?

**Comment by pbochynski** [comment]
Closed due to inactivity.
