### ISSUE TITLE
Go build error on main.go of tutorial 'examples/http-db-service'

### ISSUE THREAD

**Issue by sedacrivity** [kyma-project/examples#170]
Hi,

Trying to follow the tutorial 'Develop a service locally without using Docker' on https://kyma-project.io/docs/#tutorials-tutorials. 

First steps is building the application 'examples/http-db-service' locally using GO.  Now I am quite new to GO but I think I followed the steps correctly.

After applying the first 2 steps I am in the right subfolder and all the github packages are installed under go/src

Still I am getting a build error when executing:

CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

_package .
	main.go:14:2: use of internal package github.com/kyma-project/examples/http-db-service/internal/repository not allowed_

Using go version go1.15.3 linux/amd64

**Comment by suleymanakbas91** [comment]
Hi @sedacrivity, 

Can you please check your GOPATH environment variable? It should be pointing to the `go` folder.

**Comment by sedacrivity** [comment]
Ok this drove me a bit crazy as the GOPATH seemed to point to different folders depending in which terminal I was. In VC it seemed to be pointing to a previous installed version directory. 

Removed everything. Reinstalled and checked my .profile AND my visual code settings and now it builds without any issues.  Thanks for this learning moment and sorry about putting it as an issue here.

**Comment by suleymanakbas91** [comment]
No problem at all. Good to hear that it works now!
