### ISSUE TITLE
Examples metadata in a renderable format

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/examples#24]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

The overview of all examples with title,description, technology is available as table in the README.md.

We want to enable a nice overview as part of the product documentation, for that we need a way to integrate the examples overview table.

**Acceptance Criteria**
- the current listing is in a format so that you can embed it into the documentation
- the listing contains at least:
-- name
-- short description
-- url to example
-- url to readme
-- tags/labels for technology and domain
- Lukasz G. is informed about the new file so that he can create follow-up task for documentation overview page

**Comment**
An idea is to simply transform the table in the readme to HTML and it is still going to display nice as here: https://github.com/derberg/examples/blob/derberg-patch-1/README.md and in the UI we will always parse realtime the master version https://raw.githubusercontent.com/derberg/examples/derberg-patch-1/README.md and we will be able to transform the data into HTML and easily extract the table from it reliable way. It was verified by triggering the following code in the browser's console:
```
var xhr = new XMLHttpRequest();
--
xhr.addEventListener("load", transferComplete)
xhr.open("GET", "https://raw.githubusercontent.com/derberg/examples/derberg-patch-1/README.md");
xhr.send();
 
function transferComplete(event){
  html = new DOMParser().parseFromString(event.currentTarget.response, "text/html");
  table = html.getElementsByTagName('table');
 
  console.log(table[0].innerHTML)
}
```

**Comment by derberg** [comment]
Idea for dynamic loading of the table is blocking this issue for too long. Unfortunately implementation is not trivial and at the moment there are higher priorities. Changing the scope:

- manually write a new Examples document in docs/kyma (copy table from examples repo)
- in the readme of examples repo create a hidden note for people that change the table, that they also need to change examples document, point directly to document

**Comment by kazydek** [comment]
All PRs approved and merged:

PR - examples: https://github.com/kyma-project/examples/pull/60
PR - kyma:  https://github.com/kyma-project/kyma/pull/1571
PR - kyma - doc image update: https://github.com/kyma-project/kyma/pull/1604
