### ISSUE TITLE
Unable to access the http-db-service externally

### ISSUE THREAD

**Issue by miltonc** [kyma-project/examples#27]
Confirm these statements before you submit the issue:

- [ ] I have searched open and closed issues for duplicates.
- [ ] I have read the contributing guidelines.
---

Ran the following commands 
/build.sh
docker run -it --rm -p 8017:8017 http-db-service:latest

I can now access the docker image from http://127.0.0.1:8017
I can submit a POST and GET request on orders

Deployed to Kyma
export KYMA_EXAMPLE_ENV="qa"
kubectl apply -f deployment/deploymentOriginal.yaml -n $KYMA_EXAMPLE_ENV

Now I am not sure how to access this service.  I only see internal IP address of the service - nothing external.  Not sure what to use for host and port

curl --request GET --url http://<host>:<port>/orders

**Comment by lszymik** [comment]
As soon as the `http-db-service` is deployed it must be exposed externally. You can do it in the Console UI in services view. Please select an action: Expose API and you will be able to provide a prefix URL and security.

The service will be exposed as something like `orders.kyma.local`
 
In case of working with Kyma on the local machine you will need to add the entry into /etc/hosts to be ablet o reach your service.

**Comment by Maladie** [comment]
After exposing service as previously explained by lszymik, please try this CURL command example:

`curl -k -L --request GET --url https://<servicename>/orders`

where <servicename> is name You gave to the service while exposing. So, in this case it would be:

`curl -k -L --request GET --url https://orders.kyma.local/orders`
