### ISSUE TITLE
Examples for gateway should  use simple hostnames

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/examples#28]
Confirm these statements before you submit the issue:

- [ ] I have searched open and closed issues for duplicates.
- [ ] I have read the contributing guidelines.
---

**Description**

Resources in gateway example should use simplified hostnames to ensure the ability to run and use them on different clusters.

**Expected result**

After applying example API from gateway samples with simple host, I can access my service on the domain I'm currently working on.

**Actual result**

Currently, they refer to *.kyma.local.

**Comment by a-thaler** [comment]
I removed the domains everywhere in the examples.
