### ISSUE TITLE
Add the personservice example

### ISSUE THREAD

**Issue by kazydek** [kyma-project/examples#55]
**Description**

- Add the end-to-end `personservice` example (created by Andreas Krause) to the `examples` repo. Divide the docs (preferably by components), proofread them, add conclusions from the investigation made as part of the [this](https://app.zenhub.com/workspace/o/kyma-project/kyma/issues/792) issue.

- Expose the example in the main [`README.md`](https://github.com/kyma-project/kyma/blob/master/README.md#usage) document of the `kyma` repository.

**Reasons**

To have an end-to-end scenario in the kyma organization.

**Attachments**

Link to the example: https://github.com/kyma-incubator/examples/tree/master/personservice

**Comment by kazydek** [comment]
After a talk with @a-thaler, we decided that he would like to take a look at the example thoroughly before it is moved to the `examples` repo (e.g. introduce the open API mocks, review the existing yaml files - that will be presented as a proposal doc). Therefore, the example will not be moved at that point. Agreed with @derberg that the review of docs in the `kyma-incubator` should be put on hold as well in that case. Moving that issue to blocked until further steps are agreed on the `personservice` example.

**Comment by kazydek** [comment]
On a call with @a-thaler and @derberg it was decided that the work on the `personservice` example will be put on hold at the moment and it will no be moved to the `examples` repository. Plans for the nearest future involve rather focusing on app mocks that Huskies are working on and using them as examples for internal and external tutorials.

**Comment by derberg** [comment]
still on our bucket list

**Comment by kazydek** [comment]
I removed the `stale` label but I am not sure if we still want to process the task? @derberg ?

**Comment by derberg** [comment]
we will not add this to official examples atm, focus is on interactive getting started guides
