### ISSUE TITLE
Prow pipeline for tests/kubeless-integration

### ISSUE THREAD

**Issue by lilitgh** [kyma-project/examples#72]
**Description**

Migrate tests/kubeless-integration pipeline from Jenkins to Prow.

Migration guide is available here: https://github.com/kyma-project/test-infra/blob/master/docs/prow/migration-guide.md

Please, also update the table in this issue kyma-project/test-infra#118 after migration is done.

**Comment by suleymanakbas91** [comment]
Issue moved to [kyma-project/test-infra #257](https://github.com/kyma-project/test-infra/issues/257) via [**ZenHub**](https://www.zenhub.com/)
