### ISSUE TITLE
Example call-ec is obsolete

### ISSUE THREAD

**Issue by Maladie** [kyma-project/examples#92]
**Description**
Example call-ec is not working. File expose-ec-function.yaml uses RouteRule that is no longer used in Kyma. Example should be reviewed and changed.
Furthermore it should be changed to use the mock framework https://github.com/kyma-incubator/varkes for application integration scenarios

**Reason**
Example is not working and may be confusing to the users.

**Attachments**
Link to example: https://github.com/kyma-project/examples/tree/master/call-ec

**Comment by derberg** [comment]
example already removed
